### ISSUE TITLE
How I can to implement Prev Next navigation?

### ISSUE THREAD

**Issue by bhaktadas** [webportnoy/telegram_bot#2]
Спасибо за красивый код вашего бота!

Взял его за основу для бота с обучающими материалами (некоммерческий конспект с разделами и уроками, урок состоит из нескольких сообщений), но застрял на создании перехода между сообщениями "Назад" и "Далее". (безуспешно пробовал передавать переменные и константы из функции в функцию)

Это можно реализовать с этим скриптом?
- - -
I'm making a bot with chapters and lessons with several messages inside the lesson. Is it possible to do Previous Next navigation between messages of one lesson?

**Comment by webportnoy** [comment]
Лучше всего это сделать с помощью инлайн-кнопок.  Нажатие на инлайн кнопку обрабатывается через $this->callbackAnswer или $this->api->answerCallbackQuery, при этом в $this->result есть ссылка на сообщение, под которым нажали эту кнопку. Так можно будет определить что выведено сейчас и что надо надо показать по нажатию "далее".  Примеры можно посмотреть тут https://github.com/webportnoy/telegram_bot/blob/master/example_bot.php

Как вариант можно идентифицировать пользователя и запоминать что он вводил, чтобы в зависимости от истории принимать какие-то решения.

**Comment by bhaktadas** [comment]
Ок. Через $this->api->answerCallbackQuery я вижу, какой callback_data был у последнего сообщения и определяю, какой callback_data должен быть для предыдущего и следующего сообщения.

А дальше как это передать и выполнить? В коде клавиатуры переменные не поддерживаются - появляется ошибка про необходимость статического контента. И callbackAnswer тоже не принимает переменные:

$prev = 'less3';
$this->callbackAnswer( $text, $this->keyboards[$prev] ); 

вызывает ошибку .....reply_markup=%7B%22inline_keyboard%22%3A**null**%7D

**Comment by bhaktadas** [comment]
А может напишите готовый код? Если он сложный, то за вознаграждение.
